### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by Ebelosaurus** [daltonleibold/r4ds#2]
another issue
![story-image-abba-1024x662](https://user-images.githubusercontent.com/107601444/187930149-2c3822b2-e0d0-4858-a752-0d7bd1cb29cd.jpg)

**Comment by daltonleibold** [comment]
is this abba?

**Comment by Ebelosaurus** [comment]
yes, indeed

**Comment by daltonleibold** [comment]
is abba an issue?

**Comment by Ebelosaurus** [comment]
not really - but they are great

**Comment by daltonleibold** [comment]
then shall we close the issue?

**Comment by Ebelosaurus** [comment]
thank you for discussing this issue
